# Generated by Django 6.0 on 2026-03-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petblog', '0003_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='message',
            new_name='message_content',
        ),
    ]
