# Generated by Django 6.0 on 2026-03-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petblog', '0004_rename_message_contactmessage_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='message_content',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
