# Generated by Django 6.0 on 2026-03-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petblog', '0005_rename_message_content_contactmessage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'AUTHOR'), ('READER', 'READER')], default='READER', max_length=20),
        ),
    ]
